services:
  opt-rabbitmq:
    image: rabbitmq:4-management
    container_name: optimization-rabbitmq
    hostname: opt-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      optimization_network:
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  shared-rabbitmq:
    image: rabbitmq:4-management
    container_name: shared-rabbitmq
    hostname: shared-rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - shared_rabbitmq_data:/var/lib/rabbitmq
    networks:
      optimization_network:
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  opt-mongo:
    image: mongo:8.0
    container_name: optimization-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      optimization_network:
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://admin:password@localhost:27017/admin --authenticationDatabase admin --quiet
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  optimization_network:
    name: optimization_network
    driver: bridge

volumes:
  rabbitmq_data:
  shared_rabbitmq_data:
  mongodb_data: